[2025-10-17T21:09:26.377+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-10-17T21:09:26.386+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Airflow_Lab1.load_model_task manual__2025-10-17T21:09:01.757082+00:00 [queued]>
[2025-10-17T21:09:26.389+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Airflow_Lab1.load_model_task manual__2025-10-17T21:09:01.757082+00:00 [queued]>
[2025-10-17T21:09:26.389+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-10-17T21:09:26.394+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load_model_task> on 2025-10-17 21:09:01.757082+00:00
[2025-10-17T21:09:26.397+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=252) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-17T21:09:26.398+0000] {standard_task_runner.py:63} INFO - Started process 263 to run task
[2025-10-17T21:09:26.399+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'Airflow_Lab1', 'load_model_task', 'manual__2025-10-17T21:09:01.757082+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/***1.py', '--cfg-path', '/tmp/tmphsg_zy18']
[2025-10-17T21:09:26.400+0000] {standard_task_runner.py:91} INFO - Job 10: Subtask load_model_task
[2025-10-17T21:09:26.418+0000] {task_command.py:426} INFO - Running <TaskInstance: Airflow_Lab1.load_model_task manual__2025-10-17T21:09:01.757082+00:00 [running]> on host 819cc35ecc68
[2025-10-17T21:09:26.452+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='your_name' AIRFLOW_CTX_DAG_ID='Airflow_Lab1' AIRFLOW_CTX_TASK_ID='load_model_task' AIRFLOW_CTX_EXECUTION_DATE='2025-10-17T21:09:01.757082+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-17T21:09:01.757082+00:00'
[2025-10-17T21:09:26.453+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-10-17T21:09:26.467+0000] {logging_mixin.py:188} INFO - Optimal no. of clusters: 8
[2025-10-17T21:09:26.475+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/sklearn/utils/validation.py:2742: UserWarning: X has feature names, but KMeans was fitted without feature names
  warnings.warn(

[2025-10-17T21:09:26.482+0000] {python.py:237} INFO - Done. Returned value was: 5
[2025-10-17T21:09:26.487+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-10-17T21:09:26.504+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=Airflow_Lab1, task_id=load_model_task, run_id=manual__2025-10-17T21:09:01.757082+00:00, execution_date=20251017T210901, start_date=20251017T210926, end_date=20251017T210926
[2025-10-17T21:09:26.536+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-10-17T21:09:26.542+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-17T21:09:26.542+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
